# Generated by Django 2.2.10 on 2021-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('token', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('session', models.TextField()),
            ],
        ),
    ]
