# Generated by Django 2.2.10 on 2021-04-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210304_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelattribute',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelUnit'),
        ),
    ]
