# Generated by Django 2.2.10 on 2021-05-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20210426_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelattributemapping',
            name='Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelSource'),
        ),
        migrations.AlterField(
            model_name='datamodelattributemapping',
            name='Target_Attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelAttribute'),
        ),
        migrations.AlterField(
            model_name='datamodelcalculation',
            name='Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelSource'),
        ),
        migrations.AlterField(
            model_name='datapoints',
            name='ATTRIBUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelAttribute'),
        ),
        migrations.AlterField(
            model_name='datapoints',
            name='SOURCE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelSource'),
        ),
    ]
