# Generated by Django 2.2.10 on 2021-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210503_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodelattribute',
            name='IRI',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
