# Generated by Django 2.2.10 on 2021-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20211020_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelunit',
            name='Description',
            field=models.CharField(max_length=4096, verbose_name='Short description of unit.'),
        ),
        migrations.AlterField(
            model_name='datamodelunit',
            name='Unit',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='Unique code expressing unit.'),
        ),
    ]
