# Generated by Django 2.2.10 on 2021-12-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20211119_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamodelAttibuteSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Synonym', models.CharField(max_length=1024)),
                ('Target_Attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelAttribute')),
            ],
        ),
    ]
