# Generated by Django 2.2.10 on 2022-08-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_datamodelattibutesynonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodelattribute',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelUnit', verbose_name='Unit'),
        ),
    ]
