#!/bin/groovy
pipeline {
    agent any
    triggers {
        pollSCM('H/10 * * * 1-5')
    }
    environment {
        WORK_DIR=pwd()
        IMAGE_REPO="docker.arty.scai.fraunhofer.de/clinical-data-model/data-steward"
        IMAGE_VERSION="latest"
        CURRENT_VERSION="0.0.2"
        BUILD_NAME="clinical_data_model/biodev_cdm_data_steward"
        K8S_STATEFULSET="cdm-cdm"
    }
    stages {
        stage ('Build - Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'bio-services-arty', passwordVariable: 'password', usernameVariable: 'user')]){
                       sh "docker login docker.arty.scai.fraunhofer.de -u ${user} -p ${password}"
                       sh "docker image build . -t ${IMAGE_REPO}:${IMAGE_VERSION} -t ${IMAGE_REPO}:${CURRENT_VERSION}"
                       sh "docker image push ${IMAGE_REPO}"
                }
            }
        }

        stage ('Deploy - k8s') {
            steps {
                withKubeConfig(clusterName : "kubernetes", contextName:"bio", namespace: "bio", credentialsId: 'k8s-bioservices', serverUrl: "https://193.175.167.109:6443"){
                       sh "kubectl rollout restart statefulset ${K8S_STATEFULSET}"
                }
            }
        }
    }
    post {
        success {
            echo "Successfully updated image and deployed in k8s";
        }
       failure {
            echo "Pipeline failed";
       	    deleteDir()
        }
    }
}
