# Generated by Django 2.2.10 on 2021-04-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210304_1435'),
        ('datastewardbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('variable_raw', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=1024)),
                ('pid', models.CharField(max_length=1024)),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload.DatamodelAttribute')),
            ],
        ),
    ]
