# Generated by Django 2.2.10 on 2021-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastewardbackend', '0002_basicdatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdatapoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
