# Generated by Django 2.2.10 on 2021-05-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastewardbackend', '0003_auto_20210415_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdatapoint',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicdatapoint',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.DatamodelAttribute'),
        ),
    ]
