# Generated by Django 2.2.10 on 2021-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastewardbackend', '0004_auto_20210503_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdatapoint',
            name='timestamp',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
